title: "Roleta de Nomes"
description: "Gire a roleta de nomes online de forma rápida e divertida. Ideal para sorteios entre amigos, grupos ou eventos."
url: "https://guilherme-cunha.github.io/roleta"
author: "Guilherme Cunha"

twitter:
  username: "guicunha1188"

plugins:
  - jekyll-seo-tag
